[workspace]
authors = ["keanesc <145848994+keanesc@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "edl-emotion-recognition"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.0, <3.13"

[pypi-dependencies]
torch = { version = ">=2.9.0", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24.0", index = "https://download.pytorch.org/whl/cpu" }
numpy = ">=2.3.5, <3"
matplotlib = ">=3.10.7, <4"
tqdm = ">=4.67.1, <5"
pillow = ">=12.0.0, <13"
timm = ">=1.0.22, <2"
seaborn = ">=0.13.2, <0.14"
scikit-learn = ">=1.7.2, <2"
